"""Initial source catalog for macroeconomic time series."""

FRED_SERIES_CATALOG: dict[str, dict[str, str]] = {
    "CPIAUCSL": {
        "series_id": "CPIAUCSL",
        "description": "Headline CPI, seasonally adjusted",
        "source": "fred",
        "category": "inflation",
        "frequency_hint": "monthly",
    },
    "CPILFESL": {
        "series_id": "CPILFESL",
        "description": "Core CPI, seasonally adjusted",
        "source": "fred",
        "category": "inflation",
        "frequency_hint": "monthly",
    },
    "PCEPI": {
        "series_id": "PCEPI",
        "description": "PCE price index",
        "source": "fred",
        "category": "inflation",
        "frequency_hint": "monthly",
    },
    "PCEPILFE": {
        "series_id": "PCEPILFE",
        "description": "Core PCE price index",
        "source": "fred",
        "category": "inflation",
        "frequency_hint": "monthly",
    },
    "PAYEMS": {
        "series_id": "PAYEMS",
        "description": "Nonfarm payrolls",
        "source": "fred",
        "category": "labor",
        "frequency_hint": "monthly",
    },
    "UNRATE": {
        "series_id": "UNRATE",
        "description": "Unemployment rate",
        "source": "fred",
        "category": "labor",
        "frequency_hint": "monthly",
    },
    "AWHMAN": {
        "series_id": "AWHMAN",
        "description": "Average weekly hours manufacturing",
        "source": "fred",
        "category": "labor",
        "frequency_hint": "monthly",
    },
    "FEDFUNDS": {
        "series_id": "FEDFUNDS",
        "description": "Effective federal funds rate",
        "source": "fred",
        "category": "rates",
        "frequency_hint": "monthly",
    },
    "DGS2": {
        "series_id": "DGS2",
        "description": "2-year Treasury yield",
        "source": "fred",
        "category": "rates",
        "frequency_hint": "daily",
    },
    "DGS10": {
        "series_id": "DGS10",
        "description": "10-year Treasury yield",
        "source": "fred",
        "category": "rates",
        "frequency_hint": "daily",
    },
    "T10Y2Y": {
        "series_id": "T10Y2Y",
        "description": "10-year minus 2-year Treasury spread",
        "source": "fred",
        "category": "rates",
        "frequency_hint": "daily",
    },
    "RSAFS": {
        "series_id": "RSAFS",
        "description": "Retail sales",
        "source": "fred",
        "category": "growth/activity",
        "frequency_hint": "monthly",
    },
    "INDPRO": {
        "series_id": "INDPRO",
        "description": "Industrial production",
        "source": "fred",
        "category": "growth/activity",
        "frequency_hint": "monthly",
    },
    "MANEMP": {
        "series_id": "MANEMP",
        "description": "Manufacturing employment",
        "source": "fred",
        "category": "growth/activity",
        "frequency_hint": "monthly",
    },
    "BAMLH0A0HYM2": {
        "series_id": "BAMLH0A0HYM2",
        "description": "ICE BofA US High Yield OAS",
        "source": "fred",
        "category": "risk/credit",
        "frequency_hint": "daily",
    },
    "BAMLC0A0CM": {
        "series_id": "BAMLC0A0CM",
        "description": "ICE BofA US Corporate OAS",
        "source": "fred",
        "category": "risk/credit",
        "frequency_hint": "daily",
    },
}
